# main experimental
stimulus_type: Figures # implemented: Latin, Figures, Numbers
reaction_keys: [left, down, right]

# main visual
screen_color: #262626
text_color: black
text_size: 28

# training
training_n_blocks: 2
training_trials: {"bind":    {"two_pairs": 3, "reversed": 3, "identical": 3},
                  "no_bind": {"two_pairs": 3, "reversed": 3, "identical": 3}}
training_thinking_time: 10
training_answer_time: 10
training_wait_time: 1.5
training_wait_jitter: 1


# experiment
experiment_n_blocks: 3
experiment_trials: {"bind":    {"two_pairs": 40, "reversed": 40, "identical": 40},
                    "no_bind": {"two_pairs": 40, "reversed": 40, "identical": 40}}
experiment_thinking_time: 8
experiment_answer_time: 7
experiment_wait_time: 1.5
experiment_wait_jitter: 1

# fixation point
fixation_size: 56
fixation_color: black
fixation_text: +
fixation_time: 1

# feedback
feedback_time: 2
feedback_size: 28
feedback_color: black

# trial
elements_size: 50
images_size: 50
distance_in_pair: [30, 0]
distance_between_stim_pairs: [50, 0]
distance_between_answer_pairs: [50, 0]
stimulus_pos: [0, 100]
answers_pos: [0, -80]




